"use server";

import { feedbackSchema } from "@/constants";
import { db } from "@/firebase/admin";
import { google } from "@ai-sdk/google";
import { generateObject } from "ai";

export async function getInterviewsByUserId(userId: string): Promise<Interview[] | null> {
  if (!userId) {
  throw new Error("userId is required to fetch interviews");
}
    const interviews = await db
      .collection('interviews')
      .where('userId', '==', userId)
      .orderBy('createdAt', 'desc')
      .get();

    return interviews.docs.map((doc) => ({
        id: doc.id,
        ...doc.data(),
    })) as Interview[];
}

export async function getLatestInterviews(params: GetLatestInterviewsParams): Promise<Interview[] | null> {

    const { userId, limit = 20 } = params;

    const interviews = await db
      .collection('interviews')
      .orderBy('createdAt', 'desc')
      .where('finalized', '==', true)
      .where('userId', '!=', userId)
      .limit(limit)
      .get();

    return interviews.docs.map((doc) => ({
        id: doc.id,
        ...doc.data()
    })) as Interview[];
}

export async function getInterviewsById(id: string): Promise<Interview | null> {
    const interview = await db.collection('interviews').doc(id).get();

    return interview.data() as Interview | null;
}

export async function createFeedback(params: CreateFeedbackParams) {
    const { interviewId, userId, transcript, feedbackId } = params;

    try{
        // Validate required parameters
        if (!interviewId || !userId || !transcript || transcript.length === 0) {
            console.error("Missing required parameters for feedback creation");
            return { success: false, error: "Missing required parameters" };
        }

        const formattedTranscript = transcript.map((sentence: { role: string; content: string; }) => (
            `- ${sentence.role}: ${sentence.content}\n`
        )).join("");

        console.log("Generating feedback for interview:", interviewId);

        const { object } = await generateObject({
          model: google("gemini-2.0-flash-001", {
            structuredOutputs: false,
          }),
          schema: feedbackSchema,
          prompt: `
            You are an AI interviewer analyzing a mock interview. Your task is to evaluate the candidate based on structured categories. Be thorough and detailed in your analysis. Don't be lenient with the candidate. If there are mistakes or areas for improvement, point them out.
            Transcript:
            ${formattedTranscript}

            Please score the candidate from 0 to 100 in the following areas. Do not add categories other than the ones provided:
            - **Communication Skills**: Clarity, articulation, structured responses.
            - **Technical Knowledge**: Understanding of key concepts for the role.
            - **Problem-Solving**: Ability to analyze problems and propose solutions.
            - **Cultural Fit**: Alignment with company values and job role.
            - **Confidence & Clarity**: Confidence in responses, engagement, and clarity.
            `,
          system:
            "You are a professional interviewer analyzing a mock interview. Your task is to evaluate the candidate based on structured categories",
        });

        // Validate the generated object
        if (!object || !object.totalScore || !object.categoryScores || !object.strengths || !object.areasForImprovement || !object.finalAssessment) {
            console.error("Invalid feedback object generated by AI");
            return { success: false, error: "Invalid feedback generated" };
        }

        console.log("Feedback generated successfully, saving to database...");

        const feedback = {
          interviewId: interviewId,
          userId: userId,
          totalScore: object.totalScore,
          categoryScores: object.categoryScores,
          strengths: object.strengths,
          areasForImprovement: object.areasForImprovement,
          finalAssessment: object.finalAssessment,
          createdAt: new Date().toISOString(),
        };

        let feedbackRef;

        if (feedbackId) {
          feedbackRef = db.collection("feedback").doc(feedbackId);
        } else {
          feedbackRef = db.collection("feedback").doc();
        }

        await feedbackRef.set(feedback);

        console.log("Feedback saved successfully with ID:", feedbackRef.id);
        return { success: true, feedbackId: feedbackRef.id };
    } catch (error) {
        console.error("Error saving feedback:", error);
        return { success: false, error: error instanceof Error ? error.message : "Unknown error" };
    }
}

export async function getFeedbackByInterviewId(params: GetFeedbackByInterviewIdParams): Promise<Feedback | null> {

    const { interviewId, userId } = params;

    const feedback = await db.collection('feedback').where('interviewId', '==', interviewId).where('userId', '==', userId).limit(1).get();

    if(feedback.empty) return null;

    const feedbackDoc = feedback.docs[0];

    return {
        id: feedbackDoc.id,
        ...feedbackDoc.data()
    } as Feedback;
}

